run:
  timeout: 7m
  tests: true # includes *_test.go


linters:
  enable:
    - govet             # built-in analyzer
    - staticcheck       # static analyzer, catches bugs and inefficiencies
    - gosimple          # suggests code simplifications
    - ineffassign       # detects when unused var is assigned val
    - typecheck         # ensure code type-checks
    - errcheck          # warn if errors are ignored
    - unused
    - revive
    - gofumpt
    - gocyclo

issues:
  max-issues-per-linter: 0 # how many issues linter can report (0 = no limit)
  max-same-issues: 0



