// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/rlnc/grpc/proto/v1/rlnc.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Shard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coefficients  []byte                 `protobuf:"bytes,1,opt,name=coefficients,proto3" json:"coefficients,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shard) Reset() {
	*x = Shard{}
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shard) ProtoMessage() {}

func (x *Shard) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shard.ProtoReflect.Descriptor instead.
func (*Shard) Descriptor() ([]byte, []int) {
	return file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescGZIP(), []int{0}
}

func (x *Shard) GetCoefficients() []byte {
	if x != nil {
		return x.Coefficients
	}
	return nil
}

func (x *Shard) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type EncoderOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShredFactor   *int32                 `protobuf:"varint,1,opt,name=shred_factor,json=shredFactor,proto3,oneof" json:"shred_factor,omitempty"`
	NumShards     *int32                 `protobuf:"varint,2,opt,name=num_shards,json=numShards,proto3,oneof" json:"num_shards,omitempty"`
	NumThreads    *int32                 `protobuf:"varint,3,opt,name=num_threads,json=numThreads,proto3,oneof" json:"num_threads,omitempty"`
	Systematic    *bool                  `protobuf:"varint,4,opt,name=systematic,proto3,oneof" json:"systematic,omitempty"`
	ShredMaxSize  *int32                 `protobuf:"varint,5,opt,name=shred_max_size,json=shredMaxSize,proto3,oneof" json:"shred_max_size,omitempty"`
	PrepareData   *bool                  `protobuf:"varint,6,opt,name=prepare_data,json=prepareData,proto3,oneof" json:"prepare_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncoderOptions) Reset() {
	*x = EncoderOptions{}
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncoderOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncoderOptions) ProtoMessage() {}

func (x *EncoderOptions) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncoderOptions.ProtoReflect.Descriptor instead.
func (*EncoderOptions) Descriptor() ([]byte, []int) {
	return file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescGZIP(), []int{1}
}

func (x *EncoderOptions) GetShredFactor() int32 {
	if x != nil && x.ShredFactor != nil {
		return *x.ShredFactor
	}
	return 0
}

func (x *EncoderOptions) GetNumShards() int32 {
	if x != nil && x.NumShards != nil {
		return *x.NumShards
	}
	return 0
}

func (x *EncoderOptions) GetNumThreads() int32 {
	if x != nil && x.NumThreads != nil {
		return *x.NumThreads
	}
	return 0
}

func (x *EncoderOptions) GetSystematic() bool {
	if x != nil && x.Systematic != nil {
		return *x.Systematic
	}
	return false
}

func (x *EncoderOptions) GetShredMaxSize() int32 {
	if x != nil && x.ShredMaxSize != nil {
		return *x.ShredMaxSize
	}
	return 0
}

func (x *EncoderOptions) GetPrepareData() bool {
	if x != nil && x.PrepareData != nil {
		return *x.PrepareData
	}
	return false
}

type EncoderConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShredFactor   int32                  `protobuf:"varint,1,opt,name=shred_factor,json=shredFactor,proto3" json:"shred_factor,omitempty"`
	NumShards     int32                  `protobuf:"varint,2,opt,name=num_shards,json=numShards,proto3" json:"num_shards,omitempty"`
	NumThreads    int32                  `protobuf:"varint,3,opt,name=num_threads,json=numThreads,proto3" json:"num_threads,omitempty"`
	Systematic    bool                   `protobuf:"varint,4,opt,name=systematic,proto3" json:"systematic,omitempty"`
	ShredMaxSize  int32                  `protobuf:"varint,5,opt,name=shred_max_size,json=shredMaxSize,proto3" json:"shred_max_size,omitempty"`
	PrepareData   bool                   `protobuf:"varint,6,opt,name=prepare_data,json=prepareData,proto3" json:"prepare_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncoderConfig) Reset() {
	*x = EncoderConfig{}
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncoderConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncoderConfig) ProtoMessage() {}

func (x *EncoderConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncoderConfig.ProtoReflect.Descriptor instead.
func (*EncoderConfig) Descriptor() ([]byte, []int) {
	return file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescGZIP(), []int{2}
}

func (x *EncoderConfig) GetShredFactor() int32 {
	if x != nil {
		return x.ShredFactor
	}
	return 0
}

func (x *EncoderConfig) GetNumShards() int32 {
	if x != nil {
		return x.NumShards
	}
	return 0
}

func (x *EncoderConfig) GetNumThreads() int32 {
	if x != nil {
		return x.NumThreads
	}
	return 0
}

func (x *EncoderConfig) GetSystematic() bool {
	if x != nil {
		return x.Systematic
	}
	return false
}

func (x *EncoderConfig) GetShredMaxSize() int32 {
	if x != nil {
		return x.ShredMaxSize
	}
	return 0
}

func (x *EncoderConfig) GetPrepareData() bool {
	if x != nil {
		return x.PrepareData
	}
	return false
}

type EncodeIntoShardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputData     []byte                 `protobuf:"bytes,1,opt,name=input_data,json=inputData,proto3" json:"input_data,omitempty"`
	Options       *EncoderOptions        `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncodeIntoShardsRequest) Reset() {
	*x = EncodeIntoShardsRequest{}
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodeIntoShardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodeIntoShardsRequest) ProtoMessage() {}

func (x *EncodeIntoShardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodeIntoShardsRequest.ProtoReflect.Descriptor instead.
func (*EncodeIntoShardsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescGZIP(), []int{3}
}

func (x *EncodeIntoShardsRequest) GetInputData() []byte {
	if x != nil {
		return x.InputData
	}
	return nil
}

func (x *EncodeIntoShardsRequest) GetOptions() *EncoderOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type EncodeIntoShardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shards        []*Shard               `protobuf:"bytes,1,rep,name=shards,proto3" json:"shards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncodeIntoShardsResponse) Reset() {
	*x = EncodeIntoShardsResponse{}
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodeIntoShardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodeIntoShardsResponse) ProtoMessage() {}

func (x *EncodeIntoShardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodeIntoShardsResponse.ProtoReflect.Descriptor instead.
func (*EncodeIntoShardsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescGZIP(), []int{4}
}

func (x *EncodeIntoShardsResponse) GetShards() []*Shard {
	if x != nil {
		return x.Shards
	}
	return nil
}

type StreamShardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputData     []byte                 `protobuf:"bytes,1,opt,name=input_data,json=inputData,proto3" json:"input_data,omitempty"`
	Options       *EncoderOptions        `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamShardsRequest) Reset() {
	*x = StreamShardsRequest{}
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamShardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamShardsRequest) ProtoMessage() {}

func (x *StreamShardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamShardsRequest.ProtoReflect.Descriptor instead.
func (*StreamShardsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescGZIP(), []int{5}
}

func (x *StreamShardsRequest) GetInputData() []byte {
	if x != nil {
		return x.InputData
	}
	return nil
}

func (x *StreamShardsRequest) GetOptions() *EncoderOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type IsUncodedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shard         *Shard                 `protobuf:"bytes,1,opt,name=shard,proto3" json:"shard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsUncodedRequest) Reset() {
	*x = IsUncodedRequest{}
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsUncodedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsUncodedRequest) ProtoMessage() {}

func (x *IsUncodedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsUncodedRequest.ProtoReflect.Descriptor instead.
func (*IsUncodedRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescGZIP(), []int{6}
}

func (x *IsUncodedRequest) GetShard() *Shard {
	if x != nil {
		return x.Shard
	}
	return nil
}

type IsUncodedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsUncoded     bool                   `protobuf:"varint,1,opt,name=is_uncoded,json=isUncoded,proto3" json:"is_uncoded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsUncodedResponse) Reset() {
	*x = IsUncodedResponse{}
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsUncodedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsUncodedResponse) ProtoMessage() {}

func (x *IsUncodedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsUncodedResponse.ProtoReflect.Descriptor instead.
func (*IsUncodedResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescGZIP(), []int{7}
}

func (x *IsUncodedResponse) GetIsUncoded() bool {
	if x != nil {
		return x.IsUncoded
	}
	return false
}

type GetEncoderConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataLen       int32                  `protobuf:"varint,1,opt,name=data_len,json=dataLen,proto3" json:"data_len,omitempty"`
	Options       *EncoderOptions        `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEncoderConfigRequest) Reset() {
	*x = GetEncoderConfigRequest{}
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEncoderConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEncoderConfigRequest) ProtoMessage() {}

func (x *GetEncoderConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEncoderConfigRequest.ProtoReflect.Descriptor instead.
func (*GetEncoderConfigRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescGZIP(), []int{8}
}

func (x *GetEncoderConfigRequest) GetDataLen() int32 {
	if x != nil {
		return x.DataLen
	}
	return 0
}

func (x *GetEncoderConfigRequest) GetOptions() *EncoderOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type GetEncoderConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *EncoderConfig         `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEncoderConfigResponse) Reset() {
	*x = GetEncoderConfigResponse{}
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEncoderConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEncoderConfigResponse) ProtoMessage() {}

func (x *GetEncoderConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEncoderConfigResponse.ProtoReflect.Descriptor instead.
func (*GetEncoderConfigResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescGZIP(), []int{9}
}

func (x *GetEncoderConfigResponse) GetConfig() *EncoderConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type NewShardSetRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NumCoefficients int32                  `protobuf:"varint,1,opt,name=num_coefficients,json=numCoefficients,proto3" json:"num_coefficients,omitempty"`
	ShardLength     int32                  `protobuf:"varint,2,opt,name=shard_length,json=shardLength,proto3" json:"shard_length,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NewShardSetRequest) Reset() {
	*x = NewShardSetRequest{}
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewShardSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewShardSetRequest) ProtoMessage() {}

func (x *NewShardSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewShardSetRequest.ProtoReflect.Descriptor instead.
func (*NewShardSetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescGZIP(), []int{10}
}

func (x *NewShardSetRequest) GetNumCoefficients() int32 {
	if x != nil {
		return x.NumCoefficients
	}
	return 0
}

func (x *NewShardSetRequest) GetShardLength() int32 {
	if x != nil {
		return x.ShardLength
	}
	return 0
}

type NewShardSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardSetId    uint64                 `protobuf:"varint,1,opt,name=shard_set_id,json=shardSetId,proto3" json:"shard_set_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewShardSetResponse) Reset() {
	*x = NewShardSetResponse{}
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewShardSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewShardSetResponse) ProtoMessage() {}

func (x *NewShardSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewShardSetResponse.ProtoReflect.Descriptor instead.
func (*NewShardSetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescGZIP(), []int{11}
}

func (x *NewShardSetResponse) GetShardSetId() uint64 {
	if x != nil {
		return x.ShardSetId
	}
	return 0
}

type AddShardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardSetId    uint64                 `protobuf:"varint,1,opt,name=shard_set_id,json=shardSetId,proto3" json:"shard_set_id,omitempty"`
	Coefficients  []byte                 `protobuf:"bytes,2,opt,name=coefficients,proto3" json:"coefficients,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddShardRequest) Reset() {
	*x = AddShardRequest{}
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddShardRequest) ProtoMessage() {}

func (x *AddShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddShardRequest.ProtoReflect.Descriptor instead.
func (*AddShardRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescGZIP(), []int{12}
}

func (x *AddShardRequest) GetShardSetId() uint64 {
	if x != nil {
		return x.ShardSetId
	}
	return 0
}

func (x *AddShardRequest) GetCoefficients() []byte {
	if x != nil {
		return x.Coefficients
	}
	return nil
}

func (x *AddShardRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddShardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddShardResponse) Reset() {
	*x = AddShardResponse{}
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddShardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddShardResponse) ProtoMessage() {}

func (x *AddShardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddShardResponse.ProtoReflect.Descriptor instead.
func (*AddShardResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescGZIP(), []int{13}
}

type TryDecodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardSetId    uint64                 `protobuf:"varint,1,opt,name=shard_set_id,json=shardSetId,proto3" json:"shard_set_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TryDecodeRequest) Reset() {
	*x = TryDecodeRequest{}
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TryDecodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TryDecodeRequest) ProtoMessage() {}

func (x *TryDecodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TryDecodeRequest.ProtoReflect.Descriptor instead.
func (*TryDecodeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescGZIP(), []int{14}
}

func (x *TryDecodeRequest) GetShardSetId() uint64 {
	if x != nil {
		return x.ShardSetId
	}
	return 0
}

type TryDecodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DecodedData   []byte                 `protobuf:"bytes,1,opt,name=decoded_data,json=decodedData,proto3" json:"decoded_data,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TryDecodeResponse) Reset() {
	*x = TryDecodeResponse{}
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TryDecodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TryDecodeResponse) ProtoMessage() {}

func (x *TryDecodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TryDecodeResponse.ProtoReflect.Descriptor instead.
func (*TryDecodeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescGZIP(), []int{15}
}

func (x *TryDecodeResponse) GetDecodedData() []byte {
	if x != nil {
		return x.DecodedData
	}
	return nil
}

func (x *TryDecodeResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type RecodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardSetId    uint64                 `protobuf:"varint,1,opt,name=shard_set_id,json=shardSetId,proto3" json:"shard_set_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecodeRequest) Reset() {
	*x = RecodeRequest{}
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecodeRequest) ProtoMessage() {}

func (x *RecodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecodeRequest.ProtoReflect.Descriptor instead.
func (*RecodeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescGZIP(), []int{16}
}

func (x *RecodeRequest) GetShardSetId() uint64 {
	if x != nil {
		return x.ShardSetId
	}
	return 0
}

type RecodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shard         *Shard                 `protobuf:"bytes,1,opt,name=shard,proto3" json:"shard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecodeResponse) Reset() {
	*x = RecodeResponse{}
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecodeResponse) ProtoMessage() {}

func (x *RecodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecodeResponse.ProtoReflect.Descriptor instead.
func (*RecodeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescGZIP(), []int{17}
}

func (x *RecodeResponse) GetShard() *Shard {
	if x != nil {
		return x.Shard
	}
	return nil
}

type IsEmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardSetId    uint64                 `protobuf:"varint,1,opt,name=shard_set_id,json=shardSetId,proto3" json:"shard_set_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsEmptyRequest) Reset() {
	*x = IsEmptyRequest{}
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsEmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsEmptyRequest) ProtoMessage() {}

func (x *IsEmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsEmptyRequest.ProtoReflect.Descriptor instead.
func (*IsEmptyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescGZIP(), []int{18}
}

func (x *IsEmptyRequest) GetShardSetId() uint64 {
	if x != nil {
		return x.ShardSetId
	}
	return 0
}

type IsEmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsEmpty       bool                   `protobuf:"varint,1,opt,name=is_empty,json=isEmpty,proto3" json:"is_empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsEmptyResponse) Reset() {
	*x = IsEmptyResponse{}
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsEmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsEmptyResponse) ProtoMessage() {}

func (x *IsEmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsEmptyResponse.ProtoReflect.Descriptor instead.
func (*IsEmptyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescGZIP(), []int{19}
}

func (x *IsEmptyResponse) GetIsEmpty() bool {
	if x != nil {
		return x.IsEmpty
	}
	return false
}

type SizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardSetId    uint64                 `protobuf:"varint,1,opt,name=shard_set_id,json=shardSetId,proto3" json:"shard_set_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SizeRequest) Reset() {
	*x = SizeRequest{}
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeRequest) ProtoMessage() {}

func (x *SizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeRequest.ProtoReflect.Descriptor instead.
func (*SizeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescGZIP(), []int{20}
}

func (x *SizeRequest) GetShardSetId() uint64 {
	if x != nil {
		return x.ShardSetId
	}
	return 0
}

type SizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int32                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SizeResponse) Reset() {
	*x = SizeResponse{}
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeResponse) ProtoMessage() {}

func (x *SizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeResponse.ProtoReflect.Descriptor instead.
func (*SizeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescGZIP(), []int{21}
}

func (x *SizeResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type NumCoefficientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardSetId    uint64                 `protobuf:"varint,1,opt,name=shard_set_id,json=shardSetId,proto3" json:"shard_set_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumCoefficientsRequest) Reset() {
	*x = NumCoefficientsRequest{}
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumCoefficientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumCoefficientsRequest) ProtoMessage() {}

func (x *NumCoefficientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumCoefficientsRequest.ProtoReflect.Descriptor instead.
func (*NumCoefficientsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescGZIP(), []int{22}
}

func (x *NumCoefficientsRequest) GetShardSetId() uint64 {
	if x != nil {
		return x.ShardSetId
	}
	return 0
}

type NumCoefficientsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NumCoefficients int32                  `protobuf:"varint,1,opt,name=num_coefficients,json=numCoefficients,proto3" json:"num_coefficients,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NumCoefficientsResponse) Reset() {
	*x = NumCoefficientsResponse{}
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumCoefficientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumCoefficientsResponse) ProtoMessage() {}

func (x *NumCoefficientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumCoefficientsResponse.ProtoReflect.Descriptor instead.
func (*NumCoefficientsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescGZIP(), []int{23}
}

func (x *NumCoefficientsResponse) GetNumCoefficients() int32 {
	if x != nil {
		return x.NumCoefficients
	}
	return 0
}

type ShardLengthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardSetId    uint64                 `protobuf:"varint,1,opt,name=shard_set_id,json=shardSetId,proto3" json:"shard_set_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardLengthRequest) Reset() {
	*x = ShardLengthRequest{}
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardLengthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardLengthRequest) ProtoMessage() {}

func (x *ShardLengthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardLengthRequest.ProtoReflect.Descriptor instead.
func (*ShardLengthRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescGZIP(), []int{24}
}

func (x *ShardLengthRequest) GetShardSetId() uint64 {
	if x != nil {
		return x.ShardSetId
	}
	return 0
}

type ShardLengthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardLength   int32                  `protobuf:"varint,1,opt,name=shard_length,json=shardLength,proto3" json:"shard_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardLengthResponse) Reset() {
	*x = ShardLengthResponse{}
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardLengthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardLengthResponse) ProtoMessage() {}

func (x *ShardLengthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardLengthResponse.ProtoReflect.Descriptor instead.
func (*ShardLengthResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescGZIP(), []int{25}
}

func (x *ShardLengthResponse) GetShardLength() int32 {
	if x != nil {
		return x.ShardLength
	}
	return 0
}

type CloseShardSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardSetId    uint64                 `protobuf:"varint,1,opt,name=shard_set_id,json=shardSetId,proto3" json:"shard_set_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseShardSetRequest) Reset() {
	*x = CloseShardSetRequest{}
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseShardSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseShardSetRequest) ProtoMessage() {}

func (x *CloseShardSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseShardSetRequest.ProtoReflect.Descriptor instead.
func (*CloseShardSetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescGZIP(), []int{26}
}

func (x *CloseShardSetRequest) GetShardSetId() uint64 {
	if x != nil {
		return x.ShardSetId
	}
	return 0
}

type CloseShardSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseShardSetResponse) Reset() {
	*x = CloseShardSetResponse{}
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseShardSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseShardSetResponse) ProtoMessage() {}

func (x *CloseShardSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseShardSetResponse.ProtoReflect.Descriptor instead.
func (*CloseShardSetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescGZIP(), []int{27}
}

var File_pkg_rlnc_grpc_proto_v1_rlnc_proto protoreflect.FileDescriptor

const file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDesc = "" +
	"\n" +
	"!pkg/rlnc/grpc/proto/v1/rlnc.proto\x12\n" +
	"rlnc.proto\"?\n" +
	"\x05Shard\x12\"\n" +
	"\fcoefficients\x18\x01 \x01(\fR\fcoefficients\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xdd\x02\n" +
	"\x0eEncoderOptions\x12&\n" +
	"\fshred_factor\x18\x01 \x01(\x05H\x00R\vshredFactor\x88\x01\x01\x12\"\n" +
	"\n" +
	"num_shards\x18\x02 \x01(\x05H\x01R\tnumShards\x88\x01\x01\x12$\n" +
	"\vnum_threads\x18\x03 \x01(\x05H\x02R\n" +
	"numThreads\x88\x01\x01\x12#\n" +
	"\n" +
	"systematic\x18\x04 \x01(\bH\x03R\n" +
	"systematic\x88\x01\x01\x12)\n" +
	"\x0eshred_max_size\x18\x05 \x01(\x05H\x04R\fshredMaxSize\x88\x01\x01\x12&\n" +
	"\fprepare_data\x18\x06 \x01(\bH\x05R\vprepareData\x88\x01\x01B\x0f\n" +
	"\r_shred_factorB\r\n" +
	"\v_num_shardsB\x0e\n" +
	"\f_num_threadsB\r\n" +
	"\v_systematicB\x11\n" +
	"\x0f_shred_max_sizeB\x0f\n" +
	"\r_prepare_data\"\xdb\x01\n" +
	"\rEncoderConfig\x12!\n" +
	"\fshred_factor\x18\x01 \x01(\x05R\vshredFactor\x12\x1d\n" +
	"\n" +
	"num_shards\x18\x02 \x01(\x05R\tnumShards\x12\x1f\n" +
	"\vnum_threads\x18\x03 \x01(\x05R\n" +
	"numThreads\x12\x1e\n" +
	"\n" +
	"systematic\x18\x04 \x01(\bR\n" +
	"systematic\x12$\n" +
	"\x0eshred_max_size\x18\x05 \x01(\x05R\fshredMaxSize\x12!\n" +
	"\fprepare_data\x18\x06 \x01(\bR\vprepareData\"n\n" +
	"\x17EncodeIntoShardsRequest\x12\x1d\n" +
	"\n" +
	"input_data\x18\x01 \x01(\fR\tinputData\x124\n" +
	"\aoptions\x18\x02 \x01(\v2\x1a.rlnc.proto.EncoderOptionsR\aoptions\"E\n" +
	"\x18EncodeIntoShardsResponse\x12)\n" +
	"\x06shards\x18\x01 \x03(\v2\x11.rlnc.proto.ShardR\x06shards\"j\n" +
	"\x13StreamShardsRequest\x12\x1d\n" +
	"\n" +
	"input_data\x18\x01 \x01(\fR\tinputData\x124\n" +
	"\aoptions\x18\x02 \x01(\v2\x1a.rlnc.proto.EncoderOptionsR\aoptions\";\n" +
	"\x10IsUncodedRequest\x12'\n" +
	"\x05shard\x18\x01 \x01(\v2\x11.rlnc.proto.ShardR\x05shard\"2\n" +
	"\x11IsUncodedResponse\x12\x1d\n" +
	"\n" +
	"is_uncoded\x18\x01 \x01(\bR\tisUncoded\"j\n" +
	"\x17GetEncoderConfigRequest\x12\x19\n" +
	"\bdata_len\x18\x01 \x01(\x05R\adataLen\x124\n" +
	"\aoptions\x18\x02 \x01(\v2\x1a.rlnc.proto.EncoderOptionsR\aoptions\"M\n" +
	"\x18GetEncoderConfigResponse\x121\n" +
	"\x06config\x18\x01 \x01(\v2\x19.rlnc.proto.EncoderConfigR\x06config\"b\n" +
	"\x12NewShardSetRequest\x12)\n" +
	"\x10num_coefficients\x18\x01 \x01(\x05R\x0fnumCoefficients\x12!\n" +
	"\fshard_length\x18\x02 \x01(\x05R\vshardLength\"7\n" +
	"\x13NewShardSetResponse\x12 \n" +
	"\fshard_set_id\x18\x01 \x01(\x04R\n" +
	"shardSetId\"k\n" +
	"\x0fAddShardRequest\x12 \n" +
	"\fshard_set_id\x18\x01 \x01(\x04R\n" +
	"shardSetId\x12\"\n" +
	"\fcoefficients\x18\x02 \x01(\fR\fcoefficients\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\x12\n" +
	"\x10AddShardResponse\"4\n" +
	"\x10TryDecodeRequest\x12 \n" +
	"\fshard_set_id\x18\x01 \x01(\x04R\n" +
	"shardSetId\"F\n" +
	"\x11TryDecodeResponse\x12!\n" +
	"\fdecoded_data\x18\x01 \x01(\fR\vdecodedData\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\"1\n" +
	"\rRecodeRequest\x12 \n" +
	"\fshard_set_id\x18\x01 \x01(\x04R\n" +
	"shardSetId\"9\n" +
	"\x0eRecodeResponse\x12'\n" +
	"\x05shard\x18\x01 \x01(\v2\x11.rlnc.proto.ShardR\x05shard\"2\n" +
	"\x0eIsEmptyRequest\x12 \n" +
	"\fshard_set_id\x18\x01 \x01(\x04R\n" +
	"shardSetId\",\n" +
	"\x0fIsEmptyResponse\x12\x19\n" +
	"\bis_empty\x18\x01 \x01(\bR\aisEmpty\"/\n" +
	"\vSizeRequest\x12 \n" +
	"\fshard_set_id\x18\x01 \x01(\x04R\n" +
	"shardSetId\"\"\n" +
	"\fSizeResponse\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x05R\x04size\":\n" +
	"\x16NumCoefficientsRequest\x12 \n" +
	"\fshard_set_id\x18\x01 \x01(\x04R\n" +
	"shardSetId\"D\n" +
	"\x17NumCoefficientsResponse\x12)\n" +
	"\x10num_coefficients\x18\x01 \x01(\x05R\x0fnumCoefficients\"6\n" +
	"\x12ShardLengthRequest\x12 \n" +
	"\fshard_set_id\x18\x01 \x01(\x04R\n" +
	"shardSetId\"8\n" +
	"\x13ShardLengthResponse\x12!\n" +
	"\fshard_length\x18\x01 \x01(\x05R\vshardLength\"8\n" +
	"\x14CloseShardSetRequest\x12 \n" +
	"\fshard_set_id\x18\x01 \x01(\x04R\n" +
	"shardSetId\"\x17\n" +
	"\x15CloseShardSetResponse2\xdb\x02\n" +
	"\vRlncService\x12]\n" +
	"\x10EncodeIntoShards\x12#.rlnc.proto.EncodeIntoShardsRequest\x1a$.rlnc.proto.EncodeIntoShardsResponse\x12D\n" +
	"\fStreamShards\x12\x1f.rlnc.proto.StreamShardsRequest\x1a\x11.rlnc.proto.Shard0\x01\x12H\n" +
	"\tIsUncoded\x12\x1c.rlnc.proto.IsUncodedRequest\x1a\x1d.rlnc.proto.IsUncodedResponse\x12]\n" +
	"\x10GetEncoderConfig\x12#.rlnc.proto.GetEncoderConfigRequest\x1a$.rlnc.proto.GetEncoderConfigResponse2\xaf\x05\n" +
	"\x0fShardSetService\x12N\n" +
	"\vNewShardSet\x12\x1e.rlnc.proto.NewShardSetRequest\x1a\x1f.rlnc.proto.NewShardSetResponse\x12@\n" +
	"\x03Add\x12\x1b.rlnc.proto.AddShardRequest\x1a\x1c.rlnc.proto.AddShardResponse\x12H\n" +
	"\tTryDecode\x12\x1c.rlnc.proto.TryDecodeRequest\x1a\x1d.rlnc.proto.TryDecodeResponse\x12?\n" +
	"\x06Recode\x12\x19.rlnc.proto.RecodeRequest\x1a\x1a.rlnc.proto.RecodeResponse\x12B\n" +
	"\aIsEmpty\x12\x1a.rlnc.proto.IsEmptyRequest\x1a\x1b.rlnc.proto.IsEmptyResponse\x129\n" +
	"\x04Size\x12\x17.rlnc.proto.SizeRequest\x1a\x18.rlnc.proto.SizeResponse\x12Z\n" +
	"\x0fNumCoefficients\x12\".rlnc.proto.NumCoefficientsRequest\x1a#.rlnc.proto.NumCoefficientsResponse\x12N\n" +
	"\vShardLength\x12\x1e.rlnc.proto.ShardLengthRequest\x1a\x1f.rlnc.proto.ShardLengthResponse\x12T\n" +
	"\rCloseShardSet\x12 .rlnc.proto.CloseShardSetRequest\x1a!.rlnc.proto.CloseShardSetResponseB=Z;github.com/getoptimum/optimum-common/pkg/rlnc/grpc/proto/v1b\x06proto3"

var (
	file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescOnce sync.Once
	file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescData []byte
)

func file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescGZIP() []byte {
	file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescOnce.Do(func() {
		file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDesc), len(file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDesc)))
	})
	return file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDescData
}

var file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_pkg_rlnc_grpc_proto_v1_rlnc_proto_goTypes = []any{
	(*Shard)(nil),                    // 0: rlnc.proto.Shard
	(*EncoderOptions)(nil),           // 1: rlnc.proto.EncoderOptions
	(*EncoderConfig)(nil),            // 2: rlnc.proto.EncoderConfig
	(*EncodeIntoShardsRequest)(nil),  // 3: rlnc.proto.EncodeIntoShardsRequest
	(*EncodeIntoShardsResponse)(nil), // 4: rlnc.proto.EncodeIntoShardsResponse
	(*StreamShardsRequest)(nil),      // 5: rlnc.proto.StreamShardsRequest
	(*IsUncodedRequest)(nil),         // 6: rlnc.proto.IsUncodedRequest
	(*IsUncodedResponse)(nil),        // 7: rlnc.proto.IsUncodedResponse
	(*GetEncoderConfigRequest)(nil),  // 8: rlnc.proto.GetEncoderConfigRequest
	(*GetEncoderConfigResponse)(nil), // 9: rlnc.proto.GetEncoderConfigResponse
	(*NewShardSetRequest)(nil),       // 10: rlnc.proto.NewShardSetRequest
	(*NewShardSetResponse)(nil),      // 11: rlnc.proto.NewShardSetResponse
	(*AddShardRequest)(nil),          // 12: rlnc.proto.AddShardRequest
	(*AddShardResponse)(nil),         // 13: rlnc.proto.AddShardResponse
	(*TryDecodeRequest)(nil),         // 14: rlnc.proto.TryDecodeRequest
	(*TryDecodeResponse)(nil),        // 15: rlnc.proto.TryDecodeResponse
	(*RecodeRequest)(nil),            // 16: rlnc.proto.RecodeRequest
	(*RecodeResponse)(nil),           // 17: rlnc.proto.RecodeResponse
	(*IsEmptyRequest)(nil),           // 18: rlnc.proto.IsEmptyRequest
	(*IsEmptyResponse)(nil),          // 19: rlnc.proto.IsEmptyResponse
	(*SizeRequest)(nil),              // 20: rlnc.proto.SizeRequest
	(*SizeResponse)(nil),             // 21: rlnc.proto.SizeResponse
	(*NumCoefficientsRequest)(nil),   // 22: rlnc.proto.NumCoefficientsRequest
	(*NumCoefficientsResponse)(nil),  // 23: rlnc.proto.NumCoefficientsResponse
	(*ShardLengthRequest)(nil),       // 24: rlnc.proto.ShardLengthRequest
	(*ShardLengthResponse)(nil),      // 25: rlnc.proto.ShardLengthResponse
	(*CloseShardSetRequest)(nil),     // 26: rlnc.proto.CloseShardSetRequest
	(*CloseShardSetResponse)(nil),    // 27: rlnc.proto.CloseShardSetResponse
}
var file_pkg_rlnc_grpc_proto_v1_rlnc_proto_depIdxs = []int32{
	1,  // 0: rlnc.proto.EncodeIntoShardsRequest.options:type_name -> rlnc.proto.EncoderOptions
	0,  // 1: rlnc.proto.EncodeIntoShardsResponse.shards:type_name -> rlnc.proto.Shard
	1,  // 2: rlnc.proto.StreamShardsRequest.options:type_name -> rlnc.proto.EncoderOptions
	0,  // 3: rlnc.proto.IsUncodedRequest.shard:type_name -> rlnc.proto.Shard
	1,  // 4: rlnc.proto.GetEncoderConfigRequest.options:type_name -> rlnc.proto.EncoderOptions
	2,  // 5: rlnc.proto.GetEncoderConfigResponse.config:type_name -> rlnc.proto.EncoderConfig
	0,  // 6: rlnc.proto.RecodeResponse.shard:type_name -> rlnc.proto.Shard
	3,  // 7: rlnc.proto.RlncService.EncodeIntoShards:input_type -> rlnc.proto.EncodeIntoShardsRequest
	5,  // 8: rlnc.proto.RlncService.StreamShards:input_type -> rlnc.proto.StreamShardsRequest
	6,  // 9: rlnc.proto.RlncService.IsUncoded:input_type -> rlnc.proto.IsUncodedRequest
	8,  // 10: rlnc.proto.RlncService.GetEncoderConfig:input_type -> rlnc.proto.GetEncoderConfigRequest
	10, // 11: rlnc.proto.ShardSetService.NewShardSet:input_type -> rlnc.proto.NewShardSetRequest
	12, // 12: rlnc.proto.ShardSetService.Add:input_type -> rlnc.proto.AddShardRequest
	14, // 13: rlnc.proto.ShardSetService.TryDecode:input_type -> rlnc.proto.TryDecodeRequest
	16, // 14: rlnc.proto.ShardSetService.Recode:input_type -> rlnc.proto.RecodeRequest
	18, // 15: rlnc.proto.ShardSetService.IsEmpty:input_type -> rlnc.proto.IsEmptyRequest
	20, // 16: rlnc.proto.ShardSetService.Size:input_type -> rlnc.proto.SizeRequest
	22, // 17: rlnc.proto.ShardSetService.NumCoefficients:input_type -> rlnc.proto.NumCoefficientsRequest
	24, // 18: rlnc.proto.ShardSetService.ShardLength:input_type -> rlnc.proto.ShardLengthRequest
	26, // 19: rlnc.proto.ShardSetService.CloseShardSet:input_type -> rlnc.proto.CloseShardSetRequest
	4,  // 20: rlnc.proto.RlncService.EncodeIntoShards:output_type -> rlnc.proto.EncodeIntoShardsResponse
	0,  // 21: rlnc.proto.RlncService.StreamShards:output_type -> rlnc.proto.Shard
	7,  // 22: rlnc.proto.RlncService.IsUncoded:output_type -> rlnc.proto.IsUncodedResponse
	9,  // 23: rlnc.proto.RlncService.GetEncoderConfig:output_type -> rlnc.proto.GetEncoderConfigResponse
	11, // 24: rlnc.proto.ShardSetService.NewShardSet:output_type -> rlnc.proto.NewShardSetResponse
	13, // 25: rlnc.proto.ShardSetService.Add:output_type -> rlnc.proto.AddShardResponse
	15, // 26: rlnc.proto.ShardSetService.TryDecode:output_type -> rlnc.proto.TryDecodeResponse
	17, // 27: rlnc.proto.ShardSetService.Recode:output_type -> rlnc.proto.RecodeResponse
	19, // 28: rlnc.proto.ShardSetService.IsEmpty:output_type -> rlnc.proto.IsEmptyResponse
	21, // 29: rlnc.proto.ShardSetService.Size:output_type -> rlnc.proto.SizeResponse
	23, // 30: rlnc.proto.ShardSetService.NumCoefficients:output_type -> rlnc.proto.NumCoefficientsResponse
	25, // 31: rlnc.proto.ShardSetService.ShardLength:output_type -> rlnc.proto.ShardLengthResponse
	27, // 32: rlnc.proto.ShardSetService.CloseShardSet:output_type -> rlnc.proto.CloseShardSetResponse
	20, // [20:33] is the sub-list for method output_type
	7,  // [7:20] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pkg_rlnc_grpc_proto_v1_rlnc_proto_init() }
func file_pkg_rlnc_grpc_proto_v1_rlnc_proto_init() {
	if File_pkg_rlnc_grpc_proto_v1_rlnc_proto != nil {
		return
	}
	file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDesc), len(file_pkg_rlnc_grpc_proto_v1_rlnc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_rlnc_grpc_proto_v1_rlnc_proto_goTypes,
		DependencyIndexes: file_pkg_rlnc_grpc_proto_v1_rlnc_proto_depIdxs,
		MessageInfos:      file_pkg_rlnc_grpc_proto_v1_rlnc_proto_msgTypes,
	}.Build()
	File_pkg_rlnc_grpc_proto_v1_rlnc_proto = out.File
	file_pkg_rlnc_grpc_proto_v1_rlnc_proto_goTypes = nil
	file_pkg_rlnc_grpc_proto_v1_rlnc_proto_depIdxs = nil
}
