// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: pkg/rlnc/grpc/proto/v1/rlnc.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RlncService_EncodeIntoShards_FullMethodName = "/rlnc.proto.RlncService/EncodeIntoShards"
	RlncService_StreamShards_FullMethodName     = "/rlnc.proto.RlncService/StreamShards"
	RlncService_IsUncoded_FullMethodName        = "/rlnc.proto.RlncService/IsUncoded"
	RlncService_GetEncoderConfig_FullMethodName = "/rlnc.proto.RlncService/GetEncoderConfig"
)

// RlncServiceClient is the client API for RlncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RlncServiceClient interface {
	EncodeIntoShards(ctx context.Context, in *EncodeIntoShardsRequest, opts ...grpc.CallOption) (*EncodeIntoShardsResponse, error)
	StreamShards(ctx context.Context, in *StreamShardsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Shard], error)
	IsUncoded(ctx context.Context, in *IsUncodedRequest, opts ...grpc.CallOption) (*IsUncodedResponse, error)
	GetEncoderConfig(ctx context.Context, in *GetEncoderConfigRequest, opts ...grpc.CallOption) (*GetEncoderConfigResponse, error)
}

type rlncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRlncServiceClient(cc grpc.ClientConnInterface) RlncServiceClient {
	return &rlncServiceClient{cc}
}

func (c *rlncServiceClient) EncodeIntoShards(ctx context.Context, in *EncodeIntoShardsRequest, opts ...grpc.CallOption) (*EncodeIntoShardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncodeIntoShardsResponse)
	err := c.cc.Invoke(ctx, RlncService_EncodeIntoShards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rlncServiceClient) StreamShards(ctx context.Context, in *StreamShardsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Shard], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RlncService_ServiceDesc.Streams[0], RlncService_StreamShards_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamShardsRequest, Shard]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RlncService_StreamShardsClient = grpc.ServerStreamingClient[Shard]

func (c *rlncServiceClient) IsUncoded(ctx context.Context, in *IsUncodedRequest, opts ...grpc.CallOption) (*IsUncodedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsUncodedResponse)
	err := c.cc.Invoke(ctx, RlncService_IsUncoded_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rlncServiceClient) GetEncoderConfig(ctx context.Context, in *GetEncoderConfigRequest, opts ...grpc.CallOption) (*GetEncoderConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEncoderConfigResponse)
	err := c.cc.Invoke(ctx, RlncService_GetEncoderConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RlncServiceServer is the server API for RlncService service.
// All implementations must embed UnimplementedRlncServiceServer
// for forward compatibility.
type RlncServiceServer interface {
	EncodeIntoShards(context.Context, *EncodeIntoShardsRequest) (*EncodeIntoShardsResponse, error)
	StreamShards(*StreamShardsRequest, grpc.ServerStreamingServer[Shard]) error
	IsUncoded(context.Context, *IsUncodedRequest) (*IsUncodedResponse, error)
	GetEncoderConfig(context.Context, *GetEncoderConfigRequest) (*GetEncoderConfigResponse, error)
	mustEmbedUnimplementedRlncServiceServer()
}

// UnimplementedRlncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRlncServiceServer struct{}

func (UnimplementedRlncServiceServer) EncodeIntoShards(context.Context, *EncodeIntoShardsRequest) (*EncodeIntoShardsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EncodeIntoShards not implemented")
}
func (UnimplementedRlncServiceServer) StreamShards(*StreamShardsRequest, grpc.ServerStreamingServer[Shard]) error {
	return status.Error(codes.Unimplemented, "method StreamShards not implemented")
}
func (UnimplementedRlncServiceServer) IsUncoded(context.Context, *IsUncodedRequest) (*IsUncodedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsUncoded not implemented")
}
func (UnimplementedRlncServiceServer) GetEncoderConfig(context.Context, *GetEncoderConfigRequest) (*GetEncoderConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEncoderConfig not implemented")
}
func (UnimplementedRlncServiceServer) mustEmbedUnimplementedRlncServiceServer() {}
func (UnimplementedRlncServiceServer) testEmbeddedByValue()                     {}

// UnsafeRlncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RlncServiceServer will
// result in compilation errors.
type UnsafeRlncServiceServer interface {
	mustEmbedUnimplementedRlncServiceServer()
}

func RegisterRlncServiceServer(s grpc.ServiceRegistrar, srv RlncServiceServer) {
	// If the following call panics, it indicates UnimplementedRlncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RlncService_ServiceDesc, srv)
}

func _RlncService_EncodeIntoShards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncodeIntoShardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RlncServiceServer).EncodeIntoShards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RlncService_EncodeIntoShards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RlncServiceServer).EncodeIntoShards(ctx, req.(*EncodeIntoShardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RlncService_StreamShards_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamShardsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RlncServiceServer).StreamShards(m, &grpc.GenericServerStream[StreamShardsRequest, Shard]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RlncService_StreamShardsServer = grpc.ServerStreamingServer[Shard]

func _RlncService_IsUncoded_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsUncodedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RlncServiceServer).IsUncoded(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RlncService_IsUncoded_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RlncServiceServer).IsUncoded(ctx, req.(*IsUncodedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RlncService_GetEncoderConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEncoderConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RlncServiceServer).GetEncoderConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RlncService_GetEncoderConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RlncServiceServer).GetEncoderConfig(ctx, req.(*GetEncoderConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RlncService_ServiceDesc is the grpc.ServiceDesc for RlncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RlncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rlnc.proto.RlncService",
	HandlerType: (*RlncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EncodeIntoShards",
			Handler:    _RlncService_EncodeIntoShards_Handler,
		},
		{
			MethodName: "IsUncoded",
			Handler:    _RlncService_IsUncoded_Handler,
		},
		{
			MethodName: "GetEncoderConfig",
			Handler:    _RlncService_GetEncoderConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamShards",
			Handler:       _RlncService_StreamShards_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/rlnc/grpc/proto/v1/rlnc.proto",
}

const (
	ShardSetService_NewShardSet_FullMethodName     = "/rlnc.proto.ShardSetService/NewShardSet"
	ShardSetService_Add_FullMethodName             = "/rlnc.proto.ShardSetService/Add"
	ShardSetService_TryDecode_FullMethodName       = "/rlnc.proto.ShardSetService/TryDecode"
	ShardSetService_Recode_FullMethodName          = "/rlnc.proto.ShardSetService/Recode"
	ShardSetService_IsEmpty_FullMethodName         = "/rlnc.proto.ShardSetService/IsEmpty"
	ShardSetService_Size_FullMethodName            = "/rlnc.proto.ShardSetService/Size"
	ShardSetService_NumCoefficients_FullMethodName = "/rlnc.proto.ShardSetService/NumCoefficients"
	ShardSetService_ShardLength_FullMethodName     = "/rlnc.proto.ShardSetService/ShardLength"
	ShardSetService_CloseShardSet_FullMethodName   = "/rlnc.proto.ShardSetService/CloseShardSet"
)

// ShardSetServiceClient is the client API for ShardSetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShardSetServiceClient interface {
	NewShardSet(ctx context.Context, in *NewShardSetRequest, opts ...grpc.CallOption) (*NewShardSetResponse, error)
	Add(ctx context.Context, in *AddShardRequest, opts ...grpc.CallOption) (*AddShardResponse, error)
	TryDecode(ctx context.Context, in *TryDecodeRequest, opts ...grpc.CallOption) (*TryDecodeResponse, error)
	Recode(ctx context.Context, in *RecodeRequest, opts ...grpc.CallOption) (*RecodeResponse, error)
	IsEmpty(ctx context.Context, in *IsEmptyRequest, opts ...grpc.CallOption) (*IsEmptyResponse, error)
	Size(ctx context.Context, in *SizeRequest, opts ...grpc.CallOption) (*SizeResponse, error)
	NumCoefficients(ctx context.Context, in *NumCoefficientsRequest, opts ...grpc.CallOption) (*NumCoefficientsResponse, error)
	ShardLength(ctx context.Context, in *ShardLengthRequest, opts ...grpc.CallOption) (*ShardLengthResponse, error)
	CloseShardSet(ctx context.Context, in *CloseShardSetRequest, opts ...grpc.CallOption) (*CloseShardSetResponse, error)
}

type shardSetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShardSetServiceClient(cc grpc.ClientConnInterface) ShardSetServiceClient {
	return &shardSetServiceClient{cc}
}

func (c *shardSetServiceClient) NewShardSet(ctx context.Context, in *NewShardSetRequest, opts ...grpc.CallOption) (*NewShardSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewShardSetResponse)
	err := c.cc.Invoke(ctx, ShardSetService_NewShardSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardSetServiceClient) Add(ctx context.Context, in *AddShardRequest, opts ...grpc.CallOption) (*AddShardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddShardResponse)
	err := c.cc.Invoke(ctx, ShardSetService_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardSetServiceClient) TryDecode(ctx context.Context, in *TryDecodeRequest, opts ...grpc.CallOption) (*TryDecodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TryDecodeResponse)
	err := c.cc.Invoke(ctx, ShardSetService_TryDecode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardSetServiceClient) Recode(ctx context.Context, in *RecodeRequest, opts ...grpc.CallOption) (*RecodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecodeResponse)
	err := c.cc.Invoke(ctx, ShardSetService_Recode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardSetServiceClient) IsEmpty(ctx context.Context, in *IsEmptyRequest, opts ...grpc.CallOption) (*IsEmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsEmptyResponse)
	err := c.cc.Invoke(ctx, ShardSetService_IsEmpty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardSetServiceClient) Size(ctx context.Context, in *SizeRequest, opts ...grpc.CallOption) (*SizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SizeResponse)
	err := c.cc.Invoke(ctx, ShardSetService_Size_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardSetServiceClient) NumCoefficients(ctx context.Context, in *NumCoefficientsRequest, opts ...grpc.CallOption) (*NumCoefficientsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NumCoefficientsResponse)
	err := c.cc.Invoke(ctx, ShardSetService_NumCoefficients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardSetServiceClient) ShardLength(ctx context.Context, in *ShardLengthRequest, opts ...grpc.CallOption) (*ShardLengthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShardLengthResponse)
	err := c.cc.Invoke(ctx, ShardSetService_ShardLength_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardSetServiceClient) CloseShardSet(ctx context.Context, in *CloseShardSetRequest, opts ...grpc.CallOption) (*CloseShardSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseShardSetResponse)
	err := c.cc.Invoke(ctx, ShardSetService_CloseShardSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShardSetServiceServer is the server API for ShardSetService service.
// All implementations must embed UnimplementedShardSetServiceServer
// for forward compatibility.
type ShardSetServiceServer interface {
	NewShardSet(context.Context, *NewShardSetRequest) (*NewShardSetResponse, error)
	Add(context.Context, *AddShardRequest) (*AddShardResponse, error)
	TryDecode(context.Context, *TryDecodeRequest) (*TryDecodeResponse, error)
	Recode(context.Context, *RecodeRequest) (*RecodeResponse, error)
	IsEmpty(context.Context, *IsEmptyRequest) (*IsEmptyResponse, error)
	Size(context.Context, *SizeRequest) (*SizeResponse, error)
	NumCoefficients(context.Context, *NumCoefficientsRequest) (*NumCoefficientsResponse, error)
	ShardLength(context.Context, *ShardLengthRequest) (*ShardLengthResponse, error)
	CloseShardSet(context.Context, *CloseShardSetRequest) (*CloseShardSetResponse, error)
	mustEmbedUnimplementedShardSetServiceServer()
}

// UnimplementedShardSetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShardSetServiceServer struct{}

func (UnimplementedShardSetServiceServer) NewShardSet(context.Context, *NewShardSetRequest) (*NewShardSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NewShardSet not implemented")
}
func (UnimplementedShardSetServiceServer) Add(context.Context, *AddShardRequest) (*AddShardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedShardSetServiceServer) TryDecode(context.Context, *TryDecodeRequest) (*TryDecodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TryDecode not implemented")
}
func (UnimplementedShardSetServiceServer) Recode(context.Context, *RecodeRequest) (*RecodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Recode not implemented")
}
func (UnimplementedShardSetServiceServer) IsEmpty(context.Context, *IsEmptyRequest) (*IsEmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsEmpty not implemented")
}
func (UnimplementedShardSetServiceServer) Size(context.Context, *SizeRequest) (*SizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Size not implemented")
}
func (UnimplementedShardSetServiceServer) NumCoefficients(context.Context, *NumCoefficientsRequest) (*NumCoefficientsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NumCoefficients not implemented")
}
func (UnimplementedShardSetServiceServer) ShardLength(context.Context, *ShardLengthRequest) (*ShardLengthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShardLength not implemented")
}
func (UnimplementedShardSetServiceServer) CloseShardSet(context.Context, *CloseShardSetRequest) (*CloseShardSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseShardSet not implemented")
}
func (UnimplementedShardSetServiceServer) mustEmbedUnimplementedShardSetServiceServer() {}
func (UnimplementedShardSetServiceServer) testEmbeddedByValue()                         {}

// UnsafeShardSetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShardSetServiceServer will
// result in compilation errors.
type UnsafeShardSetServiceServer interface {
	mustEmbedUnimplementedShardSetServiceServer()
}

func RegisterShardSetServiceServer(s grpc.ServiceRegistrar, srv ShardSetServiceServer) {
	// If the following call panics, it indicates UnimplementedShardSetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShardSetService_ServiceDesc, srv)
}

func _ShardSetService_NewShardSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewShardSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardSetServiceServer).NewShardSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardSetService_NewShardSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardSetServiceServer).NewShardSet(ctx, req.(*NewShardSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardSetService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardSetServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardSetService_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardSetServiceServer).Add(ctx, req.(*AddShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardSetService_TryDecode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TryDecodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardSetServiceServer).TryDecode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardSetService_TryDecode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardSetServiceServer).TryDecode(ctx, req.(*TryDecodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardSetService_Recode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardSetServiceServer).Recode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardSetService_Recode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardSetServiceServer).Recode(ctx, req.(*RecodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardSetService_IsEmpty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsEmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardSetServiceServer).IsEmpty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardSetService_IsEmpty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardSetServiceServer).IsEmpty(ctx, req.(*IsEmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardSetService_Size_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardSetServiceServer).Size(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardSetService_Size_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardSetServiceServer).Size(ctx, req.(*SizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardSetService_NumCoefficients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NumCoefficientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardSetServiceServer).NumCoefficients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardSetService_NumCoefficients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardSetServiceServer).NumCoefficients(ctx, req.(*NumCoefficientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardSetService_ShardLength_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShardLengthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardSetServiceServer).ShardLength(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardSetService_ShardLength_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardSetServiceServer).ShardLength(ctx, req.(*ShardLengthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardSetService_CloseShardSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseShardSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardSetServiceServer).CloseShardSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardSetService_CloseShardSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardSetServiceServer).CloseShardSet(ctx, req.(*CloseShardSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShardSetService_ServiceDesc is the grpc.ServiceDesc for ShardSetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShardSetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rlnc.proto.ShardSetService",
	HandlerType: (*ShardSetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewShardSet",
			Handler:    _ShardSetService_NewShardSet_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _ShardSetService_Add_Handler,
		},
		{
			MethodName: "TryDecode",
			Handler:    _ShardSetService_TryDecode_Handler,
		},
		{
			MethodName: "Recode",
			Handler:    _ShardSetService_Recode_Handler,
		},
		{
			MethodName: "IsEmpty",
			Handler:    _ShardSetService_IsEmpty_Handler,
		},
		{
			MethodName: "Size",
			Handler:    _ShardSetService_Size_Handler,
		},
		{
			MethodName: "NumCoefficients",
			Handler:    _ShardSetService_NumCoefficients_Handler,
		},
		{
			MethodName: "ShardLength",
			Handler:    _ShardSetService_ShardLength_Handler,
		},
		{
			MethodName: "CloseShardSet",
			Handler:    _ShardSetService_CloseShardSet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/rlnc/grpc/proto/v1/rlnc.proto",
}
