# runs on version tags and PRs broadly (thorough checks)
name: Integration

on:
  push:
    # git tag marks a specific commit with a permanent name
    # so anyone can fetch the exact code for that version
    tags: [ 'v*' ] # release tags like 'v1.0.0'
  pull_request:
    branches: [ '**' ]

permissions:
  contents: read

env:
  go-version: "1.24.4"
  vuln-version: "v1.1.4"
  lint-version: "v1.64.7"
  GOPRIVATE: "github.com/getoptimum"
  GITHUB_TOKEN: ${{ secrets.OPT_ACCESS_TOKEN }}

jobs:
  vulncheck:
    name: vulncheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}
          cache: true
      - name: Configure Git for private modules
        run: git config --global url."https://${{ secrets.OPT_ACCESS_TOKEN }}:@github.com/".insteadOf "https://github.com/"
      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@${{ env.vuln-version }}
      - name: Run govulncheck
        run: make vulcheck

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}
          cache: true
      - name: Configure Git for private modules
        run: git config --global url."https://${{ secrets.OPT_ACCESS_TOKEN }}:@github.com/".insteadOf "https://github.com/"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: ${{ env.lint-version }}
          args: --timeout 10m
          only-new-issues: true

  tests:
    name: tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}
          cache: true
      - name: Configure Git for private modules
        run: git config --global url."https://${{ secrets.OPT_ACCESS_TOKEN }}:@github.com/".insteadOf "https://github.com/"
      - name: Run tests
        run: CI_RUN="true" make test
      - name: Measure test coverage
        run: make coverage
