name: Tests

on:
  pull_request:
  push:
    branches:
      - main
      - release/**
      - v*

permissions:
  contents: read
  pull-requests: read
  checks: write

concurrency:
  group: ci-${{ github.ref }}-test
  cancel-in-progress: true

env:
  go-version: "1.26.5"

jobs:
  unit-tests:
    name: unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ env.go-version }}
          cache: true

      - name: Run tests and measure coverage
        run:  make test

  fuzz-tests:
    name: fuzz tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ env.go-version }}
          cache: true

      - name: Run fuzz tests
        run: FUZZ_TIME=10s make fuzz
